# server port setting
server:
  port: 8881

spring:
  # application name setting
  application:
    name: sqld
  # profile 설정
  # Default dev db
  profiles:
    active: dev
  messages:
    basename: i18n/exception,i18n/message
    encoding: UTF-8

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: mintest707@gmail.com
#    password: ENC(2Co4AGwdRkpl/nMvyFaOqdR7MsiMCLJCwWRoGi4eA6w=)
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

# H2 Database Setting
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password: 1234

# H2 Console Setting
#  h2:
#    console:
#      enabled: true

# Mybaties Setting
#mybatis:
#  mapper-locations: classpath:mapper/*.xml

# mybatis Setting
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: "classpath:mapper/*.xml"

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.sqld_board.sqld
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true  # 캐시 사용 여부
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    enabled: true            # Swagger UI 사용여부 : 접근 경로 => <http://localhost:8080/swagger-ui/index.html>
    path: /demo-ui.html      # Swagger UI 추가 접근 경로 => <http://localhost:8080/demo-ui.html>
    tags-sorter: alpha       # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬

  # log 설정
  logging:
    level:
      org.hibernate.type: info

aes:
  algorithm: AES
  secret: "kL1uOM+G3pRxJbdXtZz2HuTmbg9CMLMgZAvn9QK9xZI="

jwt:
  secret: ".NQe9LT]Jxsdi8<;/):PdF<-IZ{l3AVJsE,A/U*;^h?" # Replace with a real secret
  access-token:
    expiration-seconds: 1800 # 30분
  refresh-token:
    expiration-seconds: 604800 # 7일

file:
#  upload-path: /Users/minboklee/Documents/upload #{mac}
#  upload-path: C:\web\upload #{window}
  #upload-path: c:/sqld/upload #{windows}

